"""
Export Service — Generate PDF and Excel output from statistical results
SPSS-style formatting with openpyxl (Excel) and WeasyPrint (PDF)
"""
import io
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── SPSS-style Excel formatting constants ─────────────────────────────────────
try:
    from openpyxl.styles import Font, PatternFill, Border, Side, Alignment

    SPSS_HEADER_FONT = Font(name="Arial", bold=True, size=9)
    SPSS_HEADER_FILL = PatternFill("solid", fgColor="D9D9D9")
    SPSS_BODY_FONT = Font(name="Arial", size=9)
    SPSS_TITLE_FONT = Font(name="Arial", bold=True, size=10)
    THIN_BORDER = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    CENTER_ALIGN = Alignment(horizontal="center", vertical="center", wrap_text=True)
    LEFT_ALIGN = Alignment(horizontal="left", vertical="center")
    RIGHT_ALIGN = Alignment(horizontal="right", vertical="center")
    _OPENPYXL_AVAILABLE = True
except ImportError:
    _OPENPYXL_AVAILABLE = False
    logger.warning("openpyxl not available — Excel export disabled")

# HTML template for PDF generation (SPSS-style)
PDF_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, Helvetica, sans-serif; font-size: 9pt; margin: 20mm; }}
  h1 {{ font-size: 12pt; color: #003f7f; border-bottom: 2px solid #003f7f; padding-bottom: 4px; }}
  h2 {{ font-size: 10pt; color: #333; margin-top: 16px; margin-bottom: 4px; }}
  h3 {{ font-size: 9pt; color: #555; margin-top: 12px; margin-bottom: 2px; }}
  table {{ border-collapse: collapse; width: auto; min-width: 300px; margin-bottom: 12px; }}
  th {{
    background-color: #e8e8e8;
    border: 1px solid #b0b0b0;
    padding: 3px 8px;
    font-weight: bold;
    text-align: center;
    font-size: 8.5pt;
  }}
  td {{
    border: 1px solid #b0b0b0;
    padding: 2px 8px;
    text-align: right;
    font-size: 8.5pt;
  }}
  td:first-child {{ text-align: left; }}
  .footnote {{ font-size: 7.5pt; color: #666; margin-top: 2px; }}
  .sig {{ color: #cc0000; }}
  @page {{
    margin: 15mm;
    @top-center {{ content: "{title}"; font-size: 8pt; color: #666; }}
    @bottom-right {{ content: "Page " counter(page) " of " counter(pages); font-size: 8pt; }}
  }}
</style>
</head>
<body>
<h1>{title}</h1>
{blocks_html}
<p class="footnote">Generated by Bernie-SPSS — Web Statistical Software</p>
</body>
</html>"""


def _block_to_html(block: Dict[str, Any]) -> str:
    """Convert a single output block to HTML."""
    title = block.get("title", "")
    subtitle = block.get("subtitle", "")
    content = block.get("content", {})

    html_parts = [f"<h2>{title}</h2>"]
    if subtitle:
        html_parts.append(f"<h3>{subtitle}</h3>")

    if isinstance(content, dict):
        headers = content.get("headers", [])
        rows = content.get("rows", [])

        if headers and rows:
            html_parts.append("<table>")
            html_parts.append("<tr>")
            for h in headers:
                html_parts.append(f"<th>{h}</th>")
            html_parts.append("</tr>")

            for row in rows:
                html_parts.append("<tr>")
                for i, cell in enumerate(row):
                    if cell is None:
                        html_parts.append("<td>.</td>")
                    elif isinstance(cell, float):
                        html_parts.append(f"<td>{cell:.3f}</td>")
                    else:
                        html_parts.append(f"<td>{cell}</td>")
                html_parts.append("</tr>")
            html_parts.append("</table>")
        else:
            # Fallback: render key-value pairs
            html_parts.append("<table>")
            for k, v in content.items():
                if k not in ("headers", "rows") and isinstance(v, (str, int, float, type(None))):
                    v_str = f"{v:.4f}" if isinstance(v, float) else str(v) if v is not None else "."
                    html_parts.append(f"<tr><td>{k}</td><td>{v_str}</td></tr>")
            html_parts.append("</table>")

    return "\n".join(html_parts)


def export_pdf(output_blocks: List[Dict[str, Any]], title: str = "Statistical Output") -> bytes:
    """
    Generate PDF from output blocks using WeasyPrint.
    Returns PDF bytes.
    """
    try:
        from weasyprint import HTML
    except ImportError:
        raise RuntimeError("WeasyPrint not installed. Install with: pip install weasyprint")

    blocks_html = "\n".join(_block_to_html(block) for block in output_blocks)
    full_html = PDF_HTML_TEMPLATE.format(title=title, blocks_html=blocks_html)

    pdf_bytes = HTML(string=full_html).write_pdf()
    return pdf_bytes


def _write_block_to_worksheet(ws: Any, block: Dict[str, Any], start_row: int) -> int:
    """
    Write a single output block to an openpyxl worksheet.
    Returns the next available row number.
    """
    from openpyxl.styles import Font, PatternFill, Alignment

    title = block.get("title", "")
    subtitle = block.get("subtitle", "")
    content = block.get("content", {})

    # Title row
    title_cell = ws.cell(row=start_row, column=1, value=title)
    title_cell.font = SPSS_TITLE_FONT
    start_row += 1

    # Subtitle
    if subtitle:
        sub_cell = ws.cell(row=start_row, column=1, value=subtitle)
        sub_cell.font = Font(name="Arial", italic=True, size=9)
        start_row += 1

    if not isinstance(content, dict):
        start_row += 1
        return start_row

    headers = content.get("headers", [])
    rows = content.get("rows", [])

    if not headers or not rows:
        # Render key-value pairs
        for k, v in content.items():
            if k not in ("headers", "rows") and isinstance(v, (str, int, float, type(None))):
                k_cell = ws.cell(row=start_row, column=1, value=str(k))
                k_cell.font = SPSS_BODY_FONT
                v_str = round(v, 3) if isinstance(v, float) else v
                v_cell = ws.cell(row=start_row, column=2, value=v_str)
                v_cell.font = SPSS_BODY_FONT
                if isinstance(v, float):
                    v_cell.number_format = "0.000"
                start_row += 1
        start_row += 1
        return start_row

    # Header row
    for col_idx, h in enumerate(headers, 1):
        cell = ws.cell(row=start_row, column=col_idx, value=str(h))
        cell.font = SPSS_HEADER_FONT
        cell.fill = SPSS_HEADER_FILL
        cell.border = THIN_BORDER
        cell.alignment = CENTER_ALIGN
    start_row += 1

    # Data rows
    for row in rows:
        for col_idx, val in enumerate(row, 1):
            cell = ws.cell(row=start_row, column=col_idx, value=val)
            cell.font = SPSS_BODY_FONT
            cell.border = THIN_BORDER
            if col_idx == 1:
                cell.alignment = LEFT_ALIGN
            else:
                cell.alignment = RIGHT_ALIGN
            if isinstance(val, float):
                cell.number_format = "0.000"  # EXACT from RESEARCH.md: 3-decimal format
        start_row += 1

    # Empty row after block
    start_row += 2
    return start_row


def export_excel(output_blocks: List[Dict[str, Any]], title: str = "Statistical Output") -> bytes:
    """
    Generate Excel workbook from output blocks using openpyxl.
    Uses SPSS_HEADER_FONT, SPSS_HEADER_FILL, 3-decimal number_format (EXACT from RESEARCH.md).
    Returns Excel bytes.
    """
    if not _OPENPYXL_AVAILABLE:
        raise RuntimeError("openpyxl not installed")

    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = "SPSS Output"

    # Title
    ws.cell(row=1, column=1, value=title).font = Font(name="Arial", bold=True, size=12)
    ws.cell(row=2, column=1, value="Generated by Bernie-SPSS").font = Font(name="Arial", italic=True, size=9, color="666666")

    current_row = 4
    for block in output_blocks:
        current_row = _write_block_to_worksheet(ws, block, current_row)

    # Auto-fit columns (approximate)
    for column_cells in ws.columns:
        max_length = 0
        col_letter = column_cells[0].column_letter
        for cell in column_cells:
            if cell.value:
                cell_len = len(str(cell.value))
                if cell_len > max_length:
                    max_length = cell_len
        adjusted_width = min(max(max_length + 2, 8), 40)
        ws.column_dimensions[col_letter].width = adjusted_width

    # Save to bytes
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
